# Generated by Django 4.1.5 on 2023-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.CharField(default='unbooked', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='clean',
            field=models.CharField(default='clean', max_length=255),
        ),
    ]
