# Generated by Django 4.1.5 on 2023-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_booking_room_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('serviceType', models.CharField(max_length=255)),
            ],
        ),
    ]
