# Generated by Django 4.1.5 on 2023-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingNumber', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('guest', models.CharField(max_length=255)),
                ('roomNumber', models.BigIntegerField()),
                ('extra', models.CharField(max_length=255)),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
