# Generated by Django 4.1.5 on 2023-01-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Booking',
        ),
    ]
