# Generated by Django 4.1.5 on 2023-02-18 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='extraServices',
            field=models.CharField(default='false', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 9, 20, 22, 162632, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
