# Generated by Django 4.1.5 on 2023-02-18 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userbookings_extraservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookings',
            name='total',
        ),
        migrations.AddField(
            model_name='userbookings',
            name='totalExtraServicePrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='totalRoomPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 20, 19, 4, 205876, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
