# Generated by Django 4.1.5 on 2023-02-18 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userbookings_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='subTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 20, 27, 45, 820899, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
