# Generated by Django 4.1.5 on 2023-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('middelName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('idCardType', models.CharField(max_length=255)),
                ('idCardNumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=255)),
                ('roomType', models.CharField(max_length=255)),
                ('roomNumber', models.CharField(max_length=255)),
                ('paymentStatus', models.CharField(max_length=255)),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
