# Generated by Django 4.1.5 on 2023-02-18 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_ischeckedin_reservation_ischeckedout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='extraServices',
            field=models.CharField(default='false', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 6, 11, 0, 233683, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
