# Generated by Django 4.1.5 on 2023-02-18 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_extraservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 9, 20, 22, 161634, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
