# Generated by Django 4.1.5 on 2023-02-18 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_bookingnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
        migrations.AddField(
            model_name='reservation',
            name='totalExtraServicePrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='totalRoomPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bookingNumber',
            field=models.CharField(default=datetime.datetime(2023, 2, 18, 20, 17, 41, 870186, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
